/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AlbumImage: typeof import('./../components/album-image/index.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElFooter: typeof import('element-plus/es')['ElFooter']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    LyricPlay: typeof import('@renderer/components/player-main/index.vue')['default']
    PageAside: typeof import('./../layout/components/pageAside.vue')['default']
    PageContent: typeof import('./../layout/components/pageContent.vue')['default']
    PageFooter: typeof import('./../layout/components/pageFooter.vue')['default']
    PageHeader: typeof import('./../layout/components/pageHeader.vue')['default']
    PlayerMain: typeof import('./../components/player-main/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UseDraggable: typeof import('@vueuse/components')['UseDraggable']
  }
}
