name: Build/release Electron app

on:
  push:
    tags:
      - v*.*.*

permissions:
  contents: write
  pages: write

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22 # 推荐使用 LTS 版本（如 18.x 或 20.x）
          cache: yarn # 启用 npm 依赖缓存
          cache-dependency-path: 'yarn.lock'

      - name: Install Dependencies
        run: yarn --non-interactive

      - name: build-linux
        if: matrix.os == 'ubuntu-latest'
        run: yarn build:linux

      - name: build-mac
        if: matrix.os == 'macos-latest'
        run: yarn build:mac

      - name: build-win
        if: matrix.os == 'windows-latest'
        run: yarn build:win

      - name: release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            dist/*.exe
            dist/*.zip
            dist/*.dmg
            dist/*.AppImage
            dist/*.snap
            dist/*.deb
            dist/*.rpm
            dist/*.tar.gz
            dist/*.yml
            dist/*.blockmap
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
